apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1
spec:
  replicas: 2
  selector:
    matchLabels:
      name: lab1
  template:
    metadata:
      labels:
        name: lab1
    spec:
      containers:
      - name: nginx
        image: nginx2:latest
        ports:
          - containerPort: 80